### ISSUE TITLE
Thank you for improving the documentation. Here are some feedback.

### ISSUE THREAD

**Issue by KoolCore** [devXadnan/comparison#2]
- The logo should have a maximum width to prevent it from being displayed incorrectly. I recommend adding a width setting option to the documentation.

- I am not clear how the comparison items are set. Can you provide more information about the logic behind them?

- The overall layout could be improved. Please see the attached image for specific suggestions.

![image.png](https://s2.loli.net/2024/01/18/EhLSPFOgImYkf18.png)

I will apreciate it if you improve it.

**Comment by KoolCore** [comment]
a great example i desire to use but paid theme.
 ![image.png](https://s2.loli.net/2024/01/18/a9DfecoVqhbk3N1.png)

**Comment by devXadnan** [comment]
The logo width issue is fixed. Please update your .css file.
-Comparison is simply working as what is your providing while other brand/competitor are not providing.
- I will improve the layout in the next version. 
If you want a comparison section similar to the example please contact me at [mrmac670@gmail.com]
